name: "build-test-install-example"
description: "Build, test, install and example workflow for CMake presets"

runs:

  using: composite

  steps:

  - name: config cpp=${{ matrix.cpp }}
    shell: bash
    run: >-
      cmake --preset default
      -Dffilesystem_cpp:BOOL=${{ matrix.cpp }}
      -DCMAKE_CXX_STANDARD=${{ matrix.cpp-std }}

  - name: Upload log failure
    if: failure()
    uses: actions/upload-artifact@v7
    with:
      archive: false
      name: cpp-${{ matrix.cpp-std }}-${{ matrix.cpp }}-${{ runner.os }}-CMakeConfigureLog.yaml
      path: build/CMakeFiles/CMakeConfigureLog.yaml

  - name: Debug workflow
    shell: bash
    run: cmake --workflow debug

  - name: Release workflow
    shell: bash
    run: cmake --workflow release

  - name: install package
    shell: bash
    run: cmake --install build

  - name: example workflow
    shell: bash
    run: cmake --workflow default
    working-directory: example
