name = "ffilesystem"
description = "Lightweight filesystem and path manipulations"
categories = "io"
version = "6.5.1"

[features]
base.cxx-flags = "-std=c++17"
base.ifx.flags = "-fpscomp:logicals"
debug.ifx.flags = "-warn"
base.nvfortran.flags = "-Munixlogical"
debug.gfortran.flags = "-Wall"

[profiles]
default = ["base"]

[build]
auto-examples = false
auto-tests = false

[install]
library = true

[library]
include-dir = ["include", "src"]
