name: ci

env:
  CMAKE_INSTALL_PREFIX: ~/libs
  CMAKE_PREFIX_PATH: ~/libs
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.c"
      - "**.h"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"
      - "!concepts/**"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux-new:

    runs-on: ubuntu-24.04
    timeout-minutes: 15

    strategy:
      matrix:
        gcc-version: [12, 13, 14]
        shared: [true, false]
        cpp: [true, false]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:

    - uses: actions/checkout@v4
    - uses: ./.github/workflows/composite-ninja
    - uses: ./.github/workflows/composite-build


  linux-flang:
  # waiting for Clang 19 + Flang. Flang 19 is needed.
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    strategy:
      matrix:
        clang-version: [18]
        cpp: [true, false]
        shared: [true, false]

    env:
      CC: clang-${{ matrix.clang-version }}
      CXX: clang++-${{ matrix.clang-version }}
      FC: gfortran-14

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/composite-ninja
    - uses: ./.github/workflows/composite-build


  gcc-9-10-11:

    runs-on: ubuntu-22.04
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        gcc-version: [9, 10, 11]
        shared: [false]
        cpp: [true, false]
        include:
        - gcc-version: 11
          shared: true
          cpp: true

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/composite-ninja
    - uses: ./.github/workflows/composite-build


  gcc-7-8:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      env:
        DEBIAN_FRONTEND: noninteractive

    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        gcc-version: [8]
        shared: [false]
        cpp: [true, false]
        include:
        - gcc-version: 7
          shared: false
          cpp: false

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}


    steps:
    - name: install compilers
      run: |
        apt update -y
        apt install -y --no-install-recommends ca-certificates gpg curl ninja-build ${{ env.CC }} ${{ env.CXX }} ${{ env.FC }}

    - name: install CMake
      run: |
        curl -s https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
        apt-get update
        test -f /usr/share/doc/kitware-archive-keyring/copyright || rm /usr/share/keyrings/kitware-archive-keyring.gpg
        apt-get install --no-install-recommends -y kitware-archive-keyring
        apt-get install --no-install-recommends -y cmake

    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-build


  cxx-std:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    strategy:
      matrix:
        cpp-std: [17, 20, 23]
        gcc-version: [14]
        cpp: [true, false]
        shared: [false]

    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
      FC: gfortran-${{ matrix.gcc-version }}

    steps:

    - uses: actions/checkout@v4
    - uses: ./.github/workflows/composite-ninja
    - uses: ./.github/workflows/composite-build


  valgrind-memory:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 10

    strategy:
      matrix:
        cpp: [true, false]

    steps:
    - name: install valgrind
      run: |
        sudo apt update
        sudo apt install --no-install-recommends valgrind

    - uses: actions/checkout@v4

    - run: ctest -Dopts="-Dffilesystem_cpp:BOOL=${{ matrix.cpp }} -Dffilesystem_BUILD_TESTING:BOOL=on" -S memcheck.cmake -E "overflow|reserved|CLI" -V

    - name: upload Valgrind log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: valgrind-log-${{ matrix.cpp }}
        path: build-Valgrind/Testing/Temporary/MemoryChecker.*.log

#------------------------------
  clang-tidy:
    if: false
    # just saving resources, it works
    runs-on: ubuntu-24.04
    needs: linux-new
    timeout-minutes: 10

    strategy:
      matrix:
        cpp: [false,true]

    steps:
    - uses: actions/checkout@v4

    - run: >-
       cmake --preset tidy
       -Dffilesystem_cpp:BOOL=${{ matrix.cpp }}
       -Dffilesystem_fortran:BOOL=off

    - run: cmake --build --preset tidy

#------------------------------
# disabled coverage due to broken Jinja import
  # linux-coverage:
  #   runs-on: ubuntu-latest
  #   needs: linux-new
  #   timeout-minutes: 10

  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.9'

  #   - name: install Gcovr
  #     run: pip install gcovr

  #   - run: cmake --preset coverage
  #   - run: cmake --build --preset coverage

  #   - name: Code coverage
  #     run: cmake --build --preset run-coverage

  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: coverage-report-html
  #       path: build-coverage/coverage/


  mac:
    runs-on: macos-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        compiler: [ {cpp: clang++, c: clang, fc: flang-new } ]
        shared: [true, false]
        cpp: [true, false]
        include:
        - compiler: {cpp: g++-14, c: gcc-14, fc: gfortran-14 }
          shared: true
          cpp: true

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
      FC: ${{ matrix.compiler.fc }}
      LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
# for flang-new https://github.com/Homebrew/homebrew-core/issues/198106

    steps:
    - name: install Flang
      if: ${{ matrix.compiler.fc == 'flang-new' }}
      run: brew install flang

    - uses: actions/checkout@v4
    - uses: ./.github/workflows/composite-ninja
    - uses: ./.github/workflows/composite-build


  cmake-older:
    timeout-minutes: 30

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cmake_version: ["3.20.6"]

    steps:

    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-cmake

    - name: configure
      run: $CMAKE -Bbuild -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/build/local -Dffilesystem_BUILD_TESTING=on --log-level=VERBOSE

    - name: build
      run: $CMAKE --build build

    - name: test
      run: $CTEST --test-dir build --output-on-failure

    - name: install package
      run: $CMAKE --install build
